// Code generated by MockGen. DO NOT EDIT.
// Source: azuredevops/internal/acceptancetests/resource_user_entitlement_test.go

// Package mock_acceptancetests is a generated GoMock package.
package mock_acceptancetests
