// Code generated by MockGen. DO NOT EDIT.
// Source: azuredevops/internal/service/permissions/resource_git_permissions_test.go

// Package mock_permissions is a generated GoMock package.
package mock_permissions
