// Code generated by MockGen. DO NOT EDIT.
// Source: azuredevops/internal/service/workitemtracking/utils/classification_test.go

// Package mock_utils is a generated GoMock package.
package mock_utils
