// Code generated by MockGen. DO NOT EDIT.
// Source: azuredevops/internal/service/taskagent/resource_agentpool_test.go

// Package mock_taskagent is a generated GoMock package.
package mock_taskagent
